############################################################################
#
# Makefile for libbase_2440
#
# 
#
# 2011-11-24		Tango		File created
# 
# 
#
############################################################################

MY_CFLAGS   = -static -I$(SOURCE_DIR)/Include -I$(TOPDIR)/Include/
MY_LIBS   := -L$(LIB_DIR)/ -lhal -lpthread   -lz -lc
SRCDIRS  += 

PROGRAM  = zlib_test
include $(TOPDIR)/Rules.mak

